export default class Resource {
    resourceNo?: string;
    sourceApp?: string;
    sourceType?: string;
    resourceType?: string;
    resourceTypeId?: number | null;
    resourceName?: string;
    displayName?: string;
    department?: string;
    email?: string;
    phone?: string;
    mobilePhone?: string;
    replacementResource?: boolean;
    fieldServiceEmail?: string;
    personalEmail?: string;
    gpsTrackingResourceNo?: string;
    homeAddress?: string;
    homeAddressGeoLong?: number | null;
    homeAddressGeoLat?: number | null;
    homePhone?: string;
    homeEmail?: string;
    homeStreet?: string;
    homeStreetNo?: string;
    homePostcode?: string;
    homeCity?: string;
    homeCounty?: string;
    homeState?: string;
    homeCountry?: string;
    homeRegion?: string;
    teamCode?: string;
    teamName?: string;
    teamType?: string;
    teamSort?: number;
    teamMemberType?: string;
    teamMemberSort?: number;
    doNotShow?: boolean;
    inServiceFrom?: string | null;
    inServiceTill?: string | null;
    exchangeIntegrationEnabled?: boolean;
    url1?: string;
    urlDescription1?: string;
    url2?: string;
    urlDescription2?: string;
    url3?: string;
    urlDescription3?: string;
    bulkPlanning?: boolean;
    bulkCapacity?: number;
    resourceGpsTrackingEnabled?: boolean;
    pin?: string;
    freeText1?: string;
    freeText2?: string;
    freeText3?: string;
    freeText4?: string;
    freeText5?: string;
    freeText6?: string;
    freeText7?: string;
    freeText8?: string;
    freeText9?: string;
    freeText10?: string;
    freeText11?: string;
    freeText12?: string;
    freeText13?: string;
    freeText14?: string;
    freeText15?: string;
    freeText16?: string;
    freeText17?: string;
    freeText18?: string;
    freeText19?: string;
    freeText20?: string;
    freeDecimal1?: number;
    freeDecimal2?: number;
    freeDecimal3?: number;
    freeDecimal4?: number;
    freeDecimal5?: number;
    freeDate1?: string | null;
    freeDate2?: string | null;
    freeDate3?: string | null;
    freeDate4?: string | null;
    freeDate5?: string | null;
    freeBit1?: boolean;
    freeBit2?: boolean;
    freeBit3?: boolean;
    freeBit4?: boolean;
    freeBit5?: boolean;
}