
const Routes = {
    ActionUri: "actionuri",
    Appointment: "appointment",
    AppointmentCategory: "appointmentCategory",
    AppointmentContainer: "appointmentContainer",
    AppointmentContent: "appointmentContent",
    AppointmentImportance: "appointmentImportance",
    AppointmentLocked: "appointmentLocked",
    AppointmentPlanningQuantity: "appointmentPlanningQuantity",
    AppointmentTimeMarker: "appointmentTimeMarker",
    AppointmentUri: "appointmentUri",
    Assignment: "assignment",
    Caption: "caption",
    Category: "categories",
    Connector: "connector",
    Container: "container",
    FilterGroup: "filterGroup",
    FilterValue: "filterValue",
    Import: "import",
    Job: "job",
    Message: "message",
    Notification: "notification",
    Pin: "pin",
    Resource: "resource",
    ResourceCalendar: "resourcecalendar",
    ResourceCapacity: "resourceCapacity",
    ResourceFilterValue: "resourceFilterValue",
    ResourceGpsTracking: "resourceGpsTracking",
    ResourceUri: "resourceuri",
    Task: "task",
    TaskContainer: "taskContainer",
    TaskFilterValue: "taskFilterValue",
    TaskLocked: "taskLocked",
    TaskUri: "taskUri",
    TimeMarker: "timeMarker",
    User: "user"
}

export default Routes;