
const Routes = {
    Task: "task",
    TaskContainer: "taskContainer",
    TaskLocked: "taskLocked",
    TaskFilterValue: "taskFilterValue",
    TaskUri: "taskUri",
    Appointment: "appointment",
    AppointmentContainer: "appointmentContainer",
    AppointmentContent: "appointmentContent",
    AppointmentImportance: "appointmentImportance",
    AppointmentLocked: "appointmentLocked",
    AppointmentPlanningQuantity: "appointmentPlanningQuantity",
    AppointmentTimeMarker: "appointmentTimeMarker",
    AppointmentUri: "appointmentUri",
    ActionUri: "actionuri",
    Caption: "caption",
    Category: "categories",
    Connector: "connector",
    Container: "container",
    FilterGroup: "filterGroup",
    FilterValue: "filterValue",
    Job: "job",
    Message: "message",
    Notification: "notification",
    Pin: "pin",
    Resource: "resource",
    ResourceGpsTracking: "resourcelocation",
    ResourceCalendar: "resourcecalendar",
    ResourceCapacity: "resourceCapacity",
    ResourceFilterValue: "resourceFilterValue",
    ResourceUri: "resourceuri",
    TimeMarker: "timemarker",
    User: "user"
}

export default Routes;