export default class Task {
    sourceApp?: string;
    sourceType?: string;
    jobNo?: string;
    taskNo?: string;
    taskType?: number;
    shortDescription?: string;
    description?: string;
    name?: string;
    type?: string;
    category?: string;
    timeMarker?: string;
    pin?: string;
    serviceNo?: string;
    serviceGroup?: string;
    serviceClass?: string;
    serviceSerialNo?: string;
    serviceName?: string;
    irisFault?: string;
    irisSymptom?: string;
    irisArea?: string;
    irisReason?: string;
    irisResolution?: string;
    skill1?: string;
    skill2?: string;
    skill3?: string;
    contractNo?: string;
    contractType?: string;
    contractDescription?: string;
    contractStartDate?: string | null;
    contractEndDate?: string | null;
    partsWarrantyStartDate?: string | null;
    partsWarrantyEndDate?: string | null;
    laborWarrantyStartDate?: string | null;
    laborWarrantyEndDate?: string | null;
    importance?: number;
    status?: string;
    expectedResponseDateTime?: string | null;
    actualResponseDateTime?: string | null;
    requestedStartDate?: string | null;
    requestedEndDate?: string | null;
    requestedStartTime?: string | null;
    requestedEndTime?: string | null;
    confirmedStartDate?: string | null;
    confirmedEndDate?: string | null;
    actualStartDate?: string | null;
    actualEndDate?: string | null;
    locationDescription?: string;
    duration?: string | null;
    durationInSeconds?: number;
    subject?: string;
    body?: string;
    infiniteTask?: boolean;
    taskOpenAsOf?: string | null;
    taskOpenTill?: string | null;
    requiredTotalDuration?: string | null;
    requiredNoResources?: number;
    appointmentEarliestAllowed?: string | null;
    appointmentLatestAllowed?: string | null;
    freeText1?: string;
    freeText2?: string;
    freeText3?: string;
    freeText4?: string;
    freeText5?: string;
    freeText6?: string;
    freeText7?: string;
    freeText8?: string;
    freeText9?: string;
    freeText10?: string;
    freeText11?: string;
    freeText12?: string;
    freeText13?: string;
    freeText14?: string;
    freeText15?: string;
    freeText16?: string;
    freeText17?: string;
    freeText18?: string;
    freeText19?: string;
    freeText20?: string;
    freeDecimal1?: number;
    freeDecimal2?: number;
    freeDecimal3?: number;
    freeDecimal4?: number;
    freeDecimal5?: number;
    freeDate1?: string | null;
    freeDate2?: string | null;
    freeDate3?: string | null;
    freeDate4?: string | null;
    freeDate5?: string | null;
    freeBit1?: boolean;
    freeBit2?: boolean;
    freeBit3?: boolean;
    freeBit4?: boolean;
    freeBit5?: boolean;
    url1?: string;
    urlDescription1?: string;
    url2?: string;
    urlDescription2?: string;
    url3?: string;
    urlDescription3?: string;
    certificateNo?: string;
    requiredTotalDurationInSeconds?: number;
    doNotCountAppointmentResource?: boolean;
    isComplete?: boolean;
    planningUOM?: string;
    planningUOMConversion?: number;
    planningQty?: number;
    useFixPlanningQty?: boolean;
    roundToUOM?: boolean;
    appointmentTemplate?: string;
    bulkPlanningQty?: number;
    startDate?: string | null;
    endDate?: string | null;
    percentDone?: number;
    schedulingMode?: number;
    baseLineStartDate?: string | null;
    baseLineEndDate?: string | null;
    baseLinePercentDone?: number;
    deadLine?: string | null;
    index?: number;
    constraintType?: number;
    constraintDatetime?: string | null;
    parentTaskNo?: string;
    calendarCode?: string;
    predecessorTaskNo?: string;
    predecessorLag?: number;
    manuallyScheduled?: boolean;
    note?: string;
    overRuleGanttPlanning?: boolean;
    ignoreCalendars?: boolean;
    containerName?: string;
    containerIndex?: number;
    checkAppointments?: boolean;
    sentFromBackOffice?: boolean;
    createJob?: boolean;



    toImportRequest(append = true) {
        return {
            "StoredProcedureName": "mboc_upsertTask",
            "ParameterNames": ["SourceApp", "SourceType", "JobNo", "TaskNo", "ShortDescription"],
            "ParameterValues": [this.sourceApp, this.sourceType, this.jobNo, this.taskNo, this.shortDescription]
        }
    }
}